CC=g++
CFLAGS=-c -Wall
LDFLAGS=-pthread
SOURCES_SERVER=game_server.cpp
SOURCES_CLIENT=game_client.cpp
OBJECTS_SERVER=$(SOURCES_SERVER:.cpp=.o)
OBJECTS_CLIENT=$(SOURCES_CLIENT:.cpp=.o)
EXECUTABLE_SERVER=game_server
EXECUTABLE_CLIENT=game_client

all: $(SOURCES_SERVER) $(SOURCES_CLIENT) $(EXECUTABLE_SERVER) $(EXECUTABLE_CLIENT)

$(EXECUTABLE_SERVER): $(OBJECTS_SERVER)
	$(CC) $(LDFLAGS) $(OBJECTS_SERVER) -o $@

$(EXECUTABLE_CLIENT): $(OBJECTS_CLIENT)
	$(CC) $(LDFLAGS) $(OBJECTS_CLIENT) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -rf $(OBJECTS_SERVER) $(OBJECTS_CLIENT) $(EXECUTABLE_SERVER) $(EXECUTABLE_CLIENT)

